# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            HydeMod
tagline:          'Hyde Modified'
description:      'The Hyde template for Jekyll modified'
baseurl:          /

author:
  name:           'Tommaso Vitali'
  url:            https://twitter.com/tommivitali

paginate:         5

# Custom vars
version:          2.1.1