# Dependencies
#markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Tom's Blog
tagline:          'Toms Blog'
description:      'Just what goes through my mind.'
baseurl:          /

author:
  name:           'Tommaso Vitali'
  url:            https://twitter.com/tommivitali

paginate:         5

# Custom vars
version:          2.1.1

url: http://tvitali.xyz